-- MySQL Script generated by MySQL Workbench
-- 11/24/16 14:10:07
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';


-- -----------------------------------------------------
-- Table `usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usuarios` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `nombre` VARCHAR(255) NULL,
  `apellido` VARCHAR(255) NULL,
  `tipo` VARCHAR(255) NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC));


-- -----------------------------------------------------
-- Table `locales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `locales` (
  `id_local` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  `direccion` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_local`));


-- -----------------------------------------------------
-- Table `imagenes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `imagenes` (
  `id_imagen` INT NOT NULL AUTO_INCREMENT,
  `imagen` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_imagen`));


-- -----------------------------------------------------
-- Table `locales_has_imagenes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `locales_has_imagenes` (
  `id_local` INT NOT NULL,
  `id_imagen` INT NOT NULL,
  PRIMARY KEY (`id_local`, `id_imagen`),
  INDEX `fk_locales_has_imagenes_imagenes1_idx` (`id_imagen` ASC),
  INDEX `fk_locales_has_imagenes_locales_idx` (`id_local` ASC),
  CONSTRAINT `fk_locales_has_imagenes_locales`
    FOREIGN KEY (`id_local`)
    REFERENCES `locales` (`id_local`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_locales_has_imagenes_imagenes1`
    FOREIGN KEY (`id_imagen`)
    REFERENCES `imagenes` (`id_imagen`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `locales_has_empleados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `locales_has_empleados` (
  `id_local` INT NOT NULL,
  `id_usuario` INT NOT NULL COMMENT 'Minino 3 empleados.',
  PRIMARY KEY (`id_local`, `id_usuario`),
  INDEX `fk_locales_has_usuarios_usuarios1_idx` (`id_usuario` ASC),
  INDEX `fk_locales_has_usuarios_locales1_idx` (`id_local` ASC),
  CONSTRAINT `fk_locales_has_usuarios_locales1`
    FOREIGN KEY (`id_local`)
    REFERENCES `locales` (`id_local`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_locales_has_usuarios_usuarios1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `propiedades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `propiedades` (
  `id_propiedad` INT NOT NULL AUTO_INCREMENT,
  `id_local` INT NOT NULL,
  `nombre` VARCHAR(255) NOT NULL,
  `direccion` FLOAT NULL,
  `precio` DOUBLE NULL,
  PRIMARY KEY (`id_propiedad`, `id_local`),
  INDEX `fk_propiedades_locales1_idx` (`id_local` ASC),
  CONSTRAINT `fk_propiedades_locales1`
    FOREIGN KEY (`id_local`)
    REFERENCES `locales` (`id_local`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `ofertas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ofertas` (
  `id_oferta` INT(11) NOT NULL AUTO_INCREMENT,
  `id_propiedad` INT NOT NULL,
  `id_local` INT NOT NULL,
  `nombre` VARCHAR(255) NULL,
  `descripcion` VARCHAR(255) NULL,
  `precio` FLOAT NULL,
  `descuento` FLOAT NULL,
  PRIMARY KEY (`id_oferta`, `id_propiedad`, `id_local`),
  INDEX `fk_propiedades_has_locales_locales1_idx` (`id_local` ASC),
  INDEX `fk_propiedades_has_locales_propiedades1_idx` (`id_propiedad` ASC),
  CONSTRAINT `fk_propiedades_has_locales_propiedades1`
    FOREIGN KEY (`id_propiedad`)
    REFERENCES `propiedades` (`id_propiedad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_propiedades_has_locales_locales1`
    FOREIGN KEY (`id_local`)
    REFERENCES `locales` (`id_local`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `locales_has_ofertas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `locales_has_ofertas` (
  `locales_id_local` INT NOT NULL,
  `locales_id_encargado` INT NOT NULL,
  `ofertas_id_oferta` INT NOT NULL,
  PRIMARY KEY (`locales_id_local`, `locales_id_encargado`, `ofertas_id_oferta`),
  INDEX `fk_locales_has_ofertas_ofertas1_idx` (`ofertas_id_oferta` ASC),
  INDEX `fk_locales_has_ofertas_locales1_idx` (`locales_id_local` ASC, `locales_id_encargado` ASC),
  CONSTRAINT `fk_locales_has_ofertas_locales1`
    FOREIGN KEY (`locales_id_local`)
    REFERENCES `locales` (`id_local`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_locales_has_ofertas_ofertas1`
    FOREIGN KEY (`ofertas_id_oferta`)
    REFERENCES `ofertas` (`id_oferta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `ofertas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ofertas` (
  `id_oferta` INT(11) NOT NULL AUTO_INCREMENT,
  `id_propiedad` INT NOT NULL,
  `id_local` INT NOT NULL,
  `nombre` VARCHAR(255) NULL,
  `descripcion` VARCHAR(255) NULL,
  `precio` FLOAT NULL,
  `descuento` FLOAT NULL,
  PRIMARY KEY (`id_oferta`, `id_propiedad`, `id_local`),
  INDEX `fk_propiedades_has_locales_locales1_idx` (`id_local` ASC),
  INDEX `fk_propiedades_has_locales_propiedades1_idx` (`id_propiedad` ASC),
  CONSTRAINT `fk_propiedades_has_locales_propiedades1`
    FOREIGN KEY (`id_propiedad`)
    REFERENCES `propiedades` (`id_propiedad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_propiedades_has_locales_locales1`
    FOREIGN KEY (`id_local`)
    REFERENCES `locales` (`id_local`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pedidos` (
  `id_pedido` INT(11) NOT NULL AUTO_INCREMENT,
  `id_local` INT NOT NULL,
  `id_usuario` INT NOT NULL,
  `nombre` VARCHAR(255) NULL,
  `descripcion` VARCHAR(255) NULL,
  `created` DATETIME NOT NULL,
  INDEX `fk_pedidos_usuarios1_idx` (`id_usuario` ASC),
  PRIMARY KEY (`id_pedido`),
  INDEX `fk_pedidos_locales1_idx` (`id_local` ASC),
  CONSTRAINT `fk_pedidos_locales1`
    FOREIGN KEY (`id_local`)
    REFERENCES `locales` (`id_local`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedidos_usuarios1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ventas` (
  `id_venta` INT(11) NOT NULL AUTO_INCREMENT,
  `id_propiedad` INT NOT NULL,
  `id_oferta` INT(11) NULL COMMENT 'Si no es null la venta es por una oferta.',
  `precio` DOUBLE NULL,
  `created` DATETIME NOT NULL,
  `usuarios_id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_venta`, `id_propiedad`, `usuarios_id_usuario`),
  INDEX `fk_ventas_propiedades1_idx` (`id_propiedad` ASC),
  INDEX `fk_ventas_ofertas1_idx` (`id_oferta` ASC),
  INDEX `fk_ventas_usuarios1_idx` (`usuarios_id_usuario` ASC),
  CONSTRAINT `fk_ventas_propiedades1`
    FOREIGN KEY (`id_propiedad`)
    REFERENCES `propiedades` (`id_propiedad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ventas_ofertas1`
    FOREIGN KEY (`id_oferta`)
    REFERENCES `ofertas` (`id_oferta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ventas_usuarios1`
    FOREIGN KEY (`usuarios_id_usuario`)
    REFERENCES `usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `propiedades_has_imagenes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `propiedades_has_imagenes` (
  `id_propiedad` INT NOT NULL,
  `id_imagen` INT NOT NULL,
  PRIMARY KEY (`id_propiedad`, `id_imagen`),
  INDEX `fk_propiedades_has_imagenes_imagenes1_idx` (`id_imagen` ASC),
  INDEX `fk_propiedades_has_imagenes_propiedades1_idx` (`id_propiedad` ASC),
  CONSTRAINT `fk_propiedades_has_imagenes_propiedades1`
    FOREIGN KEY (`id_propiedad`)
    REFERENCES `propiedades` (`id_propiedad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_propiedades_has_imagenes_imagenes1`
    FOREIGN KEY (`id_imagen`)
    REFERENCES `imagenes` (`id_imagen`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `locales_has_encargado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `locales_has_encargado` (
  `id_local` INT NOT NULL,
  `id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_local`, `id_usuario`),
  INDEX `fk_locales_has_usuarios_usuarios2_idx` (`id_usuario` ASC),
  INDEX `fk_locales_has_usuarios_locales2_idx` (`id_local` ASC),
  UNIQUE INDEX `id_local_UNIQUE` (`id_local` ASC),
  UNIQUE INDEX `id_usuario_UNIQUE` (`id_usuario` ASC),
  CONSTRAINT `fk_locales_has_usuarios_locales2`
    FOREIGN KEY (`id_local`)
    REFERENCES `locales` (`id_local`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_locales_has_usuarios_usuarios2`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

INSERT INTO `usuarios` (`id_usuario`, `tipo`, `username`, `password`, `email`, `nombre`, `apellido`) VALUES
(1, 'administrador', 'administrador', '91f5167c34c400758115c2a6826ec2e3', 'administrador@administrador.com', 'administrador', 'administrador'),
(2, 'encargado', 'encargado', 'cb0d0277094bffbf04eceb3a6091cfaa', 'encargado@encargado.com', 'encargado', 'encargado'),
(3, 'cliente', 'cliente', '4983a0ab83ed86e0e7213c8783940193', 'cliente@cliente.com', 'cliente', 'cliente'),
(4, 'empleado', 'empleado', '088ef99bff55c67dc863f83980a66a9b', 'empleado@empleado.com', 'empleado', 'empleado');


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
